### ISSUE TITLE
NPE on server close

### ISSUE THREAD

**Issue by LemADEC** [Shadows-of-Fire/Parabox#13]
As of Parabox-1.12.2-1.1.1, when server fails to boot, Parabox closes with an NPE:
```
[01:39:45] [Server thread/INFO] [mcjty.lib.varia.Logging]: Cleaning up all world data: 0 data blobs
[01:39:45] [Server thread/WARN] [opencomputers]: Error handling file saving: Did the server never start?
[01:39:45] [Server thread/INFO] [Parabox]: Saving Parabox world data.
[01:39:45] [Server thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Parabox (parabox)
[01:39:45] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: Caused by: java.lang.NullPointerException
[01:39:45] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at net.darkhax.parabox.util.WorldSpaceTimeManager.onGameInstanceClose(WorldSpaceTimeManager.java:64)
[01:39:45] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at net.darkhax.parabox.Parabox.serverStop(Parabox.java:85)
[01:39:45] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[01:39:45] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[01:39:45] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[01:39:45] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at java.lang.reflect.Method.invoke(Method.java:498)
[01:39:45] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
[01:39:45] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
[01:39:45] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[01:39:45] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at java.lang.reflect.Method.invoke(Method.java:498)
[01:39:45] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[01:39:45] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[01:39:45] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[01:39:45] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[01:39:45] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[01:39:45] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[01:39:45] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[01:39:45] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
[01:39:45] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
[01:39:45] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[01:39:45] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[01:39:45] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[01:39:45] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at java.lang.reflect.Method.invoke(Method.java:498)
[01:39:45] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[01:39:45] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[01:39:45] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[01:39:45] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[01:39:45] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[01:39:45] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[01:39:45] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[01:39:45] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at net.minecraftforge.fml.common.LoadController.redirect$onPost$zza000(LoadController.java:553)
[01:39:45] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
[01:39:45] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at net.minecraftforge.fml.common.Loader.serverStopped(Loader.java:847)
[01:39:45] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStopped(FMLCommonHandler.java:508)
[01:39:45] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:587)
[01:39:45] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at java.lang.Thread.run(Thread.java:748)
```
This is with SkyFactory4 4.0.3.

**Comment by Shadows-of-Fire** [comment]
That's a bit strange, I thought I made that unable to happen.  Please delete your parabox.json file and see if the issue persists.

**Comment by Shadows-of-Fire** [comment]
This is only if the server fails starting up and then triggers a shutdown for some other reason?  How exactly does that happen?

**Comment by LemADEC** [comment]
We're hunting a world corruption related to MystCraft and possibly SpongeForge. Once the map is corrupted, server crashes when trying to load the map. I suspect that NPE is preventing the server to close completely, probably due to another bug in Forge.

**Comment by Shadows-of-Fire** [comment]
Well that should patch the error.  Unfortunately the development of parabox has taken a bit of a turn so it may be a bit before that fix goes live.
