### ISSUE TITLE
does not work on sponge at all 

### ISSUE THREAD

**Issue by Bucky420** [Shadows-of-Fire/Parabox#5]
[18:43:52] [Server thread/INFO] [Parabox]: Saving Parabox world data.
[18:43:52] [Server thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Parabox (parabox)
 Caused by: java.lang.NullPointerException
 	at net.darkhax.parabox.util.WorldSpaceTimeManager.onGameInstanceClose(WorldSpaceTimeManager.java:64)
 	at net.darkhax.parabox.Parabox.serverStop(Parabox.java:85)
 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 	at java.lang.reflect.Method.invoke(Method.java:498)
 	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
 	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 	at java.lang.reflect.Method.invoke(Method.java:498)
 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
 	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
 	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 	at java.lang.reflect.Method.invoke(Method.java:498)
 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
 	at net.minecraftforge.fml.common.LoadController.redirect$onPost$zza000(LoadController.java:553)
 	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
 	at net.minecraftforge.fml.common.Loader.serverStopped(Loader.java:847)
 	at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStopped(FMLCommonHandler.java:508)
 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:587)
 	at java.lang.Thread.run(Thread.java:748)

**Comment by Bucky420** [comment]
this makes the server not crash but simply just stop working and ticking and commands stop working as well this happens after the world loads im still looking in to things and seeing if this a sponge issue 
[latest.log](https://github.com/Shadows-of-Fire/Parabox/files/3086429/latest.log)

**Comment by Bucky420** [comment]
foamfix issue ... and me being dumb
